# Generated by Django 5.1.7 on 2025-03-19 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('added', 'Dodano przyczepkę'), ('edited', 'Edytowano przyczepkę'), ('deleted', 'Usunięto przyczepkę'), ('status_change', 'Zmiana statusu'), ('ping', 'Pingowanie')], max_length=20)),
                ('message', models.TextField()),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rentalapp.trailer')),
            ],
        ),
    ]
