# Generated by Django 5.1.7 on 2025-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_trailerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
