# Generated by Django 5.1.7 on 2025-03-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0005_warehouselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouselog',
            name='quantity_taken',
            field=models.IntegerField(default=0),
        ),
    ]
