# Generated by Django 5.1.7 on 2025-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_company_remove_rental_user_rental_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
