# Generated by Django 5.1.7 on 2025-04-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0008_rental_monthly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='trailer',
        ),
        migrations.AlterField(
            model_name='rental',
            name='company',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentalapp.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='RentalTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_trailers', to='rentalapp.rental')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.trailer')),
            ],
        ),
    ]
