# Generated by Django 5.1.7 on 2025-05-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0009_remove_rental_trailer_alter_rental_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
