# Generated by Django 5.1.7 on 2025-05-08 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0011_rentalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
