# Generated by Django 5.1.7 on 2025-05-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0013_rental_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerlog',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='rentalapp.trailer'),
        ),
    ]
