# Generated by Django 5.1.7 on 2025-05-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0014_alter_trailerlog_trailer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
